on: [push, pull_request]
name: Clippy
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy
            override: true

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings
